FROM golang:latest AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build fileserver/main.go


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8082

ENTRYPOINT ["./main"]
